### ISSUE TITLE
Reuseable module with parameters/overrides

### ISSUE THREAD

**Issue by iTNTPiston** [iTNTPiston/celer#15]
Currently we only have reuseable modules without parameters like
```yaml
MyModule: something something something

AnotherModule:
  - step
  - __use__ MyModule
  - step
```

Would be nice to have MyModule take parameters and enable more code sharing/dedupe

Proposal 1: use existing extend format
```yaml
MyModule: something something something # this must be a single step, not an array of steps

AnotherModule:
  - step
  - __use__ MyModule:
      comment: hello # apply overrides
  - step
```

Proposal 2: use generic/macro-like syntax. This will be more powerful and harder to implement
```yaml
MyModuleMacro<X,Y,Z>: 
   use {{X}}:
     comment: {{Y}}
     {{Z}}

AnotherModule:
  - step
  - __use__ MyModule<something, hello, "icon: my-icon">:
  - step
```
